services:
  frontend:
    build: ./frontend
    volumes:
      - frontend_dist:/app/dist
    command: >
      /bin/bash -c "rm -rf /app/dist/* && npm run build"
    depends_on:
      - backend
    
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - backend_uploads:/usr/src/app/uploads
    
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - frontend_dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  frontend_dist:
  backend_uploads: