export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  ME_REQUEST: "ME_REQUEST",
  ME_SUCCESS: "ME_SUCCESS",
  ME_FAILURE: "ME_FAILURE",

  MY_INVOICES_REQUEST: "MY_INVOICES_REQUEST",
  MY_INVOICES_SUCCESS: "MY_INVOICES_SUCCESS",
  MY_INVOICES_FAILURE: "MY_INVOICES_FAILURE",

  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  REQUEST_VERIFY_EMAIL_REQUEST: "REQUEST_VERIFY_EMAIL_REQUEST",
  REQUEST_VERIFY_EMAIL_SUCCESS: "REQUEST_VERIFY_EMAIL_SUCCESS",
  REQUEST_VERIFY_EMAIL_FAILURE: "REQUEST_VERIFY_EMAIL_FAILURE",

  UPDATE_PASSWORD_REQUEST: 'UPDATE_PASSWORD_REQUEST',
  UPDATE_PASSWORD_SUCCESS: 'UPDATE_PASSWORD_SUCCESS',
  UPDATE_PASSWORD_FAILURE: 'UPDATE_PASSWORD_FAILURE',

  RESET_PASSWORD_REQUEST: "RESET_PASSWORD_REQUEST",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_FAILURE: "RESET_PASSWORD_FAILURE",

  FORGOT_PASSWORD_REQUEST: "FORGOT_PASSWORD_REQUEST",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_FAILURE: "FORGOT_PASSWORD_FAILURE",

  UPDATE_PROFILE_REQUEST: "UPDATE_PROFILE_REQUEST",
  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
  UPDATE_PROFILE_FAILURE: "UPDATE_PROFILE_FAILURE",

  GET_CLIENTS_REQUEST: "GET_CLIENTS_REQUEST",
  GET_CLIENTS_SUCCESS: "GET_CLIENTS_SUCCESS",
  GET_CLIENTS_FAILURE: "GET_CLIENTS_FAILURE",

  ADD_EDITOR_REQUEST: "ADD_EDITOR_REQUEST",
  ADD_EDITOR_SUCCESS: "ADD_EDITOR_SUCCESS",
  ADD_EDITOR_FAILURE: "ADD_EDITOR_FAILURE",

  UPDATE_EDITOR_REQUEST: "UPDATE_EDITOR_REQUEST",
  UPDATE_EDITOR_SUCCESS: "UPDATE_EDITOR_SUCCESS",
  UPDATE_EDITOR_FAILURE: "UPDATE_EDITOR_FAILURE",

  GET_EDITOR_REQUEST: "GET_EDITOR_REQUEST",
  GET_EDITOR_SUCCESS: "GET_EDITOR_SUCCESS",
  GET_EDITOR_FAILURE: "GET_EDITOR_FAILURE",

  GET_DASHBOARD_REQUEST: "GET_DASHBOARD_REQUEST",
  GET_DASHBOARD_SUCCESS: "GET_DASHBOARD_SUCCESS",
  GET_DASHBOARD_FAILURE: "GET_DASHBOARD_FAILURE",

  GET_SUBS_PAGE_DETAILS_REQUEST: "GET_SUBS_PAGE_DETAILS_REQUEST",
  GET_SUBS_PAGE_DETAILS_SUCCESS: "GET_SUBS_PAGE_DETAILS_SUCCESS",
  GET_SUBS_PAGE_DETAILS_FAILURE: "GET_SUBS_PAGE_DETAILS_FAILURE",

  UPDATE_SUBS_PAGE_DETAILS_REQUEST: "UPDATE_SUBS_PAGE_DETAILS_REQUEST",
  UPDATE_SUBS_PAGE_DETAILS_SUCCESS: "UPDATE_SUBS_PAGE_DETAILS_SUCCESS",
  UPDATE_SUBS_PAGE_DETAILS_FAILURE: "UPDATE_SUBS_PAGE_DETAILS_FAILURE",
};
