export const businessConstants = {

    BUSINESS_LIST_REQUEST: "BUSINESS_LIST_REQUEST",
    BUSINESS_LIST_SUCCESS: "BUSINESS_LIST_SUCCESS",
    BUSINESS_LIST_FAILURE: "BUSINESS_LIST_FAILURE",

    SINGLE_BUSINESS_REQUEST: "SINGLE_BUSINESS_REQUEST",
    SINGLE_BUSINESS_SUCCESS: "SINGLE_BUSINESS_SUCCESS",
    SINGLE_BUSINESS_FAILURE: "SINGLE_BUSINESS_FAILURE",

    ADD_EDIT_BUSINESS_REQUEST: "ADD_EDIT_BUSINESS_REQUEST",
    ADD_EDIT_BUSINESS_SUCCESS: "ADD_EDIT_BUSINESS_SUCCESS",
    ADD_EDIT_BUSINESS_FAILURE: "ADD_EDIT_BUSINESS_FAILURE",

    PUBLISHED_BUSINESS_REQUEST: "PUBLISHED_BUSINESS_REQUEST",
    PUBLISHED_BUSINESS_SUCCESS: "PUBLISHED_BUSINESS_SUCCESS",
    PUBLISHED_BUSINESS_FAILURE: "PUBLISHED_BUSINESS_FAILURE",

    DELETE_BUSINESS_REQUEST: "DELETE_BUSINESS_REQUEST",
    DELETE_BUSINESS_SUCCESS: "DELETE_BUSINESS_SUCCESS",
    DELETE_BUSINESS_FAILURE: "DELETE_BUSINESS_FAILURE",

    DOWNLOAD_DOC_BUSINESS_REQUEST: "DOWNLOAD_DOC_BUSINESS_REQUEST",
    DOWNLOAD_DOC_BUSINESS_SUCCESS: "DOWNLOAD_DOC_BUSINESS_SUCCESS",
    DOWNLOAD_DOC_BUSINESS_FAILURE: "DOWNLOAD_DOC_BUSINESS_FAILURE",

};
