export const coursesConstants = {

    COURSE_LIST_REQUEST: "COURSE_LIST_REQUEST",
    COURSE_LIST_SUCCESS: "COURSE_LIST_SUCCESS",
    COURSE_LIST_FAILURE: "COURSE_LIST_FAILURE",

    SINGLE_COURSE_REQUEST: "SINGLE_COURSE_REQUEST",
    SINGLE_COURSE_SUCCESS: "SINGLE_COURSE_SUCCESS",
    SINGLE_COURSE_FAILURE: "SINGLE_COURSE_FAILURE",

    ADD_EDIT_COURSE_REQUEST: "ADD_EDIT_COURSE_REQUEST",
    ADD_EDIT_COURSE_SUCCESS: "ADD_EDIT_COURSE_SUCCESS",
    ADD_EDIT_COURSE_FAILURE: "ADD_EDIT_COURSE_FAILURE",

    PUBLISHED_COURSE_REQUEST: "PUBLISHED_COURSE_REQUEST",
    PUBLISHED_COURSE_SUCCESS: "PUBLISHED_COURSE_SUCCESS",
    PUBLISHED_COURSE_FAILURE: "PUBLISHED_COURSE_FAILURE",

    DELETE_COURSE_REQUEST: "DELETE_COURSE_REQUEST",
    DELETE_COURSE_SUCCESS: "DELETE_COURSE_SUCCESS",
    DELETE_COURSE_FAILURE: "DELETE_COURSE_FAILURE",

};
