export const podcastsConstants = {

    PODCASTS_LIST_REQUEST: "PODCASTS_LIST_REQUEST",
    PODCASTS_LIST_SUCCESS: "PODCASTS_LIST_SUCCESS",
    PODCASTS_LIST_FAILURE: "PODCASTS_LIST_FAILURE",

    SINGLE_PODCASTS_REQUEST: "SINGLE_PODCASTS_REQUEST",
    SINGLE_PODCASTS_SUCCESS: "SINGLE_PODCASTS_SUCCESS",
    SINGLE_PODCASTS_FAILURE: "SINGLE_PODCASTS_FAILURE",

    ADD_EDIT_PODCASTS_REQUEST: "ADD_EDIT_PODCASTS_REQUEST",
    ADD_EDIT_PODCASTS_SUCCESS: "ADD_EDIT_PODCASTS_SUCCESS",
    ADD_EDIT_PODCASTS_FAILURE: "ADD_EDIT_PODCASTS_FAILURE",

    PUBLISHED_PODCASTS_REQUEST: "PUBLISHED_PODCASTS_REQUEST",
    PUBLISHED_PODCASTS_SUCCESS: "PUBLISHED_PODCASTS_SUCCESS",
    PUBLISHED_PODCASTS_FAILURE: "PUBLISHED_PODCASTS_FAILURE",

    DELETE_PODCASTS_REQUEST: "DELETE_PODCASTS_REQUEST",
    DELETE_PODCASTS_SUCCESS: "DELETE_PODCASTS_SUCCESS",
    DELETE_PODCASTS_FAILURE: "DELETE_PODCASTS_FAILURE",

};
