export const subscriptionConstants = {

    GET_PLANS_REQUEST: "GET_PLANS_REQUEST",
    GET_PLANS_SUCCESS: "GET_PLANS_SUCCESS",
    GET_PLANS_FAILURE: "GET_PLANS_FAILURE",

    ADD_PAYMENT_METHOD_REQUEST: "ADD_PAYMENT_METHOD_REQUEST",
    ADD_PAYMENT_METHOD_SUCCESS: "ADD_PAYMENT_METHOD_SUCCESS",
    ADD_PAYMENT_METHOD_FAILURE: "ADD_PAYMENT_METHOD_FAILURE",

    GET_PAYMENT_METHODS_REQUEST: "GET_PAYMENT_METHODS_REQUEST",
    GET_PAYMENT_METHODS_SUCCESS: "GET_PAYMENT_METHODS_SUCCESS",
    GET_PAYMENT_METHODS_FAILURE: "GET_PAYMENT_METHODS_FAILURE",

    CREATE_SUBSCRIPTION_REQUEST: "CREATE_SUBSCRIPTION_REQUEST",
    CREATE_SUBSCRIPTION_SUCCESS: "CREATE_SUBSCRIPTION_SUCCESS",
    CREATE_SUBSCRIPTION_FAILURE: "CREATE_SUBSCRIPTION_FAILURE",

    GET_MY_SUBSCRIPTION_REQUEST: "GET_MY_SUBSCRIPTION_REQUEST",
    GET_MY_SUBSCRIPTION_SUCCESS: "GET_MY_SUBSCRIPTION_SUCCESS",
    GET_MY_SUBSCRIPTION_FAILURE: "GET_MY_SUBSCRIPTION_FAILURE",

    CANCEL_SUBSCRIPTION_REQUEST: "CANCEL_SUBSCRIPTION_REQUEST",
    CANCEL_SUBSCRIPTION_SUCCESS: "CANCEL_SUBSCRIPTION_SUCCESS",
    CANCEL_SUBSCRIPTION_FAILURE: "CANCEL_SUBSCRIPTION_FAILURE",

    REMOVE_PAYMENT_METHOD_REQUEST: "REMOVE_PAYMENT_METHOD_REQUEST",
    REMOVE_PAYMENT_METHOD_SUCCESS: "REMOVE_PAYMENT_METHOD_SUCCESS",
    REMOVE_PAYMENT_METHOD_FAILURE: "REMOVE_PAYMENT_METHOD_FAILURE",


};
